#!/usr/bin/env python3
"""
Script to replot training metrics from CSV log files.

This script reads CSV files generated by the training script and replots
the data using the same plotting function.

Usage:
    python replot_training_metrics.py [csv_file]
    
If no CSV file is specified, it will look for all CSV files in the logs directory
and replot them.
"""

import os
import sys
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Add parent directory to path to import plotting function
parent_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, parent_dir)

try:
    from grpo_early_exit import _plot_training_metrics
except ImportError:
    # Try alternative import path
    sys.path.insert(0, os.path.dirname(parent_dir))
    from grpo_early_exit.grpo_early_exit import _plot_training_metrics


def replot_from_csv(csv_path, output_dir=None):
    """
    Read CSV file and replot the data.
    
    Args:
        csv_path: Path to CSV file containing training metrics
        output_dir: Directory to save replotted images (default: plots/ in parent directory)
    """
    if not os.path.exists(csv_path):
        print(f"Error: CSV file not found: {csv_path}")
        return
    
    # Default output directory is plots/ in parent directory
    if output_dir is None:
        parent_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
        output_dir = os.path.join(parent_dir, 'plots')
    
    print(f"\nReading data from: {csv_path}")
    df = pd.read_csv(csv_path)
    
    # Extract data columns
    entropies = df['entropy'].tolist() if 'entropy' in df.columns else None
    latencies = df['latency'].tolist() if 'latency' in df.columns else None
    num_layers = df['num_layers'].tolist() if 'num_layers' in df.columns else None
    temperatures = df['temperature'].tolist() if 'temperature' in df.columns else None
    rewards = df['reward'].tolist() if 'reward' in df.columns else None
    entropy_penalties = df['entropy_penalty'].tolist() if 'entropy_penalty' in df.columns else None
    prefill_freq = df['prefill_freq'].tolist() if 'prefill_freq' in df.columns else None
    decode_freq = df['decode_freq'].tolist() if 'decode_freq' in df.columns else None
    batch_size = df['batch_size'].tolist() if 'batch_size' in df.columns else None
    per_token_latency = df['per_token_latency'].tolist() if 'per_token_latency' in df.columns else None
    decode_latency = df['decode_latency'].tolist() if 'decode_latency' in df.columns else None
    
    # Get episode number (should be same for all rows)
    episode = int(df['episode'].iloc[0]) if 'episode' in df.columns and len(df) > 0 else 1
    
    # Get max_temp if available
    max_temp = float(df['max_temp'].iloc[0]) if 'max_temp' in df.columns and pd.notna(df['max_temp'].iloc[0]) else None
    
    # Convert None strings to actual None
    def convert_none(val):
        if pd.isna(val) or val == 'None' or val == '':
            return None
        try:
            return float(val)
        except (ValueError, TypeError):
            return None
    
    if entropies:
        entropies = [convert_none(e) for e in entropies]
    if temperatures:
        temperatures = [convert_none(t) for t in temperatures]
    if rewards:
        rewards = [convert_none(r) for r in rewards]
    if entropy_penalties:
        entropy_penalties = [convert_none(ep) for ep in entropy_penalties]
    if prefill_freq:
        prefill_freq = [convert_none(f) for f in prefill_freq]
    if decode_freq:
        decode_freq = [convert_none(f) for f in decode_freq]
    if batch_size:
        batch_size = [convert_none(b) for b in batch_size]
    if per_token_latency:
        per_token_latency = [convert_none(l) for l in per_token_latency]
    if decode_latency:
        decode_latency = [convert_none(l) for l in decode_latency]
    
    # Determine output filename (keep same name as CSV, just change extension)
    csv_basename = os.path.basename(csv_path)
    plot_filename = csv_basename.replace('.csv', '.png')
    
    output_path = os.path.join(output_dir, plot_filename)
    os.makedirs(output_dir, exist_ok=True)
    
    print(f"Replotting data...")
    print(f"  Episode: {episode}")
    print(f"  Steps: {len(df)}")
    print(f"  Entropy data: {sum(1 for e in entropies if e is not None) if entropies else 0} valid values")
    print(f"  Latency data: {len(latencies) if latencies else 0} values")
    print(f"  Layer data: {len(num_layers) if num_layers else 0} values")
    print(f"  Temperature data: {sum(1 for t in temperatures if t is not None) if temperatures else 0} valid values")
    print(f"  Reward data: {len(rewards) if rewards else 0} values")
    print(f"  Entropy penalty data: {len(entropy_penalties) if entropy_penalties else 0} values")
    print(f"  Prefill freq data: {sum(1 for f in prefill_freq if f is not None) if prefill_freq else 0} valid values")
    print(f"  Decode freq data: {sum(1 for f in decode_freq if f is not None) if decode_freq else 0} valid values")
    print(f"  Batch size data: {sum(1 for b in batch_size if b is not None) if batch_size else 0} valid values")
    print(f"  Per-token latency data: {sum(1 for l in per_token_latency if l is not None) if per_token_latency else 0} valid values")
    print(f"  Decode latency data: {sum(1 for l in decode_latency if l is not None) if decode_latency else 0} valid values")
    print(f"  Max temp: {max_temp}°C" if max_temp else "  Max temp: Not specified")
    
    # Replot using the same function
    _plot_training_metrics(
        entropies=entropies,
        latencies=latencies,
        num_layers=num_layers,
        current_episode=episode,
        save_path=output_path,
        rewards=rewards,
        entropy_penalties=entropy_penalties,
        temperatures=temperatures,
        max_temp=max_temp,
        prefill_freq=prefill_freq,
        decode_freq=decode_freq,
        batch_size=batch_size,
        per_token_latency=per_token_latency,
        decode_latency=decode_latency
    )
    
    print(f"\nReplot saved to: {output_path}")


def main():
    """Main function to handle command line arguments."""
    if len(sys.argv) > 1:
        # Plot specific CSV file
        csv_path = sys.argv[1]
        replot_from_csv(csv_path)
    else:
        # Plot all CSV files in logs directory
        logs_dir = os.path.dirname(os.path.abspath(__file__))
        if not os.path.exists(logs_dir):
            print(f"Error: Logs directory not found: {logs_dir}")
            return
        
        csv_files = [f for f in os.listdir(logs_dir) if f.endswith('.csv')]
        
        if not csv_files:
            print(f"No CSV files found in {logs_dir}")
            return
        
        print(f"Found {len(csv_files)} CSV file(s) in {logs_dir}")
        print("=" * 60)
        
        for csv_file in sorted(csv_files):
            csv_path = os.path.join(logs_dir, csv_file)
            print(f"\nProcessing: {csv_file}")
            print("-" * 60)
            replot_from_csv(csv_path)
        
        print("\n" + "=" * 60)
        print("All replots completed!")


if __name__ == "__main__":
    main()

